// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU1R6O3Z1KHEHrTSmK-yV_Hvx6d81UjGM',
    appId: '1:599259224692:web:2d5827b2a11573282dcf21',
    messagingSenderId: '599259224692',
    projectId: 'smart-haryana',
    authDomain: 'smart-haryana.firebaseapp.com',
    storageBucket: 'smart-haryana.firebasestorage.app',
    measurementId: 'G-E75J3450BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvCmeUX5-jcro6COu6ptYFY_RT7IiqYlc',
    appId: '1:599259224692:android:6150538522ed126f2dcf21',
    messagingSenderId: '599259224692',
    projectId: 'smart-haryana',
    storageBucket: 'smart-haryana.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU1R6O3Z1KHEHrTSmK-yV_Hvx6d81UjGM',
    appId: '1:599259224692:web:ad6c6e9098a3d3092dcf21',
    messagingSenderId: '599259224692',
    projectId: 'smart-haryana',
    authDomain: 'smart-haryana.firebaseapp.com',
    storageBucket: 'smart-haryana.firebasestorage.app',
    measurementId: 'G-SWNRRWNQXD',
  );
}
